# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/socce/Downloads/Zybo-Z7-10-Pcam-5C-hw.xpr/Zybo-Z7-HW/Zybo-Z7-HW.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0.xci
# IP: The module: 'system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/socce/Downloads/Zybo-Z7-10-Pcam-5C-hw.xpr/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/socce/Downloads/Zybo-Z7-10-Pcam-5C-hw.xpr/Zybo-Z7-HW/Zybo-Z7-HW.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0.xci
# IP: The module: 'system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/socce/Downloads/Zybo-Z7-10-Pcam-5C-hw.xpr/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
